### ISSUE TITLE
Setup of new instance comes up with Procfile error

### ISSUE THREAD

**Issue by rowlandm** [NotTheOnlyOne/not_the_only_one#1]
When running honcho start -e config.env -f Local I get error

2021-02-14 07:01:58 [2774] [ERROR] Procfile does not exist or is not a file'

**Comment by rowlandm** [comment]
Procfile copied from https://github.com/hack4impact/flask-base/blob/master/Procfile

**Comment by rowlandm** [comment]
(base) rowlandm@AspireR14:~/code/not_the_only_one/webapp$ foreman

Command 'foreman' not found, but can be installed with:

sudo apt install ruby-foreman

(base) rowlandm@AspireR14:~/code/not_the_only_one/webapp$ sudo apt install ruby-foreman

**Comment by rowlandm** [comment]
after installing foreman start actually does something

(base) rowlandm@AspireR14:~/code/not_the_only_one/webapp$ foreman start
07:20:31 web.1    | started with pid 3850
07:20:31 worker.1 | started with pid 3851
07:20:31 web.1    | [2021-02-14 07:20:31 +1100] [3850] [INFO] Starting gunicorn 20.0.4
07:20:31 web.1    | [2021-02-14 07:20:31 +1100] [3850] [INFO] Listening at: http://0.0.0.0:5000 (3850)
07:20:31 web.1    | [2021-02-14 07:20:31 +1100] [3850] [INFO] Using worker: sync
07:20:31 web.1    | [2021-02-14 07:20:31 +1100] [3855] [INFO] Booting worker with pid: 3855
07:20:31 worker.1 | Importing environment from .env file
07:20:31 worker.1 | THIS APP IS IN DEBUG MODE.                 YOU SHOULD NOT SEE THIS IN PRODUCTION.
07:20:31 worker.1 | Traceback (most recent call last):
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
07:20:31 worker.1 |     sock = self._connect()
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
07:20:31 worker.1 |     raise err07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/flask_script/__init__.py", line 386, in handle
07:20:31 worker.1 |     res = handle(*args, **config)
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/flask_script/commands.py", line 216, in __call__
07:20:31 worker.1 |     return self.run(*args, **kwargs)
07:20:31 worker.1 |   File "manage.py", line 183, in run_worker
07:20:31 worker.1 |     worker.work()
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/rq/worker.py", line 535, in work
07:20:31 worker.1 |     self.register_birth()
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/rq/worker.py", line 278, in register_birth
07:20:31 worker.1 |     if self.connection.exists(self.key) and \
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/redis/client.py", line 1581, in exists
07:20:31 worker.1 |     return self.execute_command('EXISTS', *names)
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
07:20:31 worker.1 |     conn = self.connection or pool.get_connection(command_name, **options)
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
07:20:31 worker.1 |     connection.connect()
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
07:20:31 worker.1 |     raise ConnectionError(self._error_message(e))
07:20:31 worker.1 | redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
07:20:32 worker.1 | exited with code 1
07:20:32 system   | sending SIGTERM to all processes
07:20:32 web.1    | [2021-02-14 07:20:32 +1100] [3850] [INFO] Handling signal: term
07:20:32 web.1    | [2021-02-14 07:20:32 +1100] [3855] [INFO] Worker exiting (pid: 3855)
07:20:32 web.1    | Importing environment from .env file
07:20:32 web.1    | THIS APP IS IN DEBUG MODE.                 YOU SHOULD NOT SEE THIS IN PRODUCTION.
07:20:32 web.1    | [2021-02-14 07:20:32 +1100] [3850] [INFO] Shutting down: Master
07:20:32 web.1    | exited with code 0
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
07:20:31 worker.1 |     sock.connect(socket_address)
07:20:31 worker.1 | ConnectionRefusedError: [Errno 111] Connection refused
07:20:31 worker.1 | 
07:20:31 worker.1 | During handling of the above exception, another exception occurred:
07:20:31 worker.1 | 
07:20:31 worker.1 | Traceback (most recent call last):
07:20:31 worker.1 |   File "manage.py", line 200, in <module>
07:20:31 worker.1 |     manager.run()
07:20:31 worker.1 |   File "/home/rowlandm/miniconda3/lib/python3.8/site-packages/flask_script/__init__.py", line 417, in run
07:20:31 worker.1 |     result = self.handle(argv[0], argv[1:])

**Comment by rowlandm** [comment]
It didn't work with honcho - must be for production.

I did get it running with:

python manage.py runserver -h 0.0.0.0
